### ISSUE TITLE
Helpers - SNS messages support

### ISSUE THREAD

**Issue by ngr** [sosw/sosw#175]
Implement `get_lambda_event_from_sns_message` and `is_event_from_sns` in helpers.
We have it for example in `td_sl_deleted` lambda.

**Comment by markbulgakov** [comment]
@nimirium 

What if we don't have a `Message` key in the event from `Sns` by some reason? Should we return an empty dict or the event, that we've received as a param of the function?

I talked with Nick, he think that we should return either empty dict or Raise.And he prefer to raise.

**Comment by ngr** [comment]
Looks like this is already in #189 
Please confirm.

**Comment by markbulgakov** [comment]
Yes, it's in #189
