### ISSUE TITLE
Implement get_ddbc for custom row_mappers

### ISSUE THREAD

**Issue by ngr** [sosw/sosw#289]
Implement in Processor something like this and add documentation and tests:

```
    def get_ddbc(self, prefix: str) -> DynamoDbClient:
        """ Lazy init of custom DDB clients. """
        names = list([x.split('_dynamo_db_config')[0] for x in
                      filter(lambda x: x.endswith('_dynamo_db_config'), self.config)])
        if prefix not in names:
            raise ValueError(f"get_ddbc() method supports only prefixes: {names}")

        name = f"{prefix}_dynamo_db_client"
        if not getattr(self, name, None):
            setattr(self, name, DynamoDbClient(self.config[f'{prefix}_dynamo_db_config']))

        return getattr(self, name)
```

**Comment by ngr** [comment]
Just a brief description:
This is a **lazy** DynamoDB client initialization supporting multiple DDB clients configured to work with different tables and `row_mappers`. Could be very helpful instead of the raw `boto3.client` when you need to validate schemas, transform DDB syntax to `dict`, etc.

**Comment by ngr** [comment]
Hi @kreanimator ,
Is there any progress with this task? Are you going to implement it anytime soon?

Important so that we will have it in the `app.Processor` ASAP

**Comment by kreanimator** [comment]
Hi, I'll try to finish it this week🙌
